### ISSUE TITLE
[Help] Relationship Error

### ISSUE THREAD

**Issue by ghost** [tomvlk/sweet-orm#2]
I seem to be having trouble with relationships.

```
Exception information:

           Date: Apr 22, 2016 22:37PM

           Message: Property is not set at entity 'App\Models\User' when trying to solve relationship fetching.

           Code: 0

           File: /home/kingorgg/projects/srpf/vendor/tomvlk/sweet-orm/src/SweetORM/Structure/RelationManager.php

           Line: 107

           Stack trace:

           #0 /home/kingorgg/projects/srpf/vendor/tomvlk/sweet-orm/src/SweetORM/EntityManager.php(231): SweetORM\Structure\RelationManager->fetch('roles')
#1 /home/kingorgg/projects/srpf/vendor/tomvlk/sweet-orm/src/SweetORM/Entity.php(50): SweetORM\EntityManager->getLazy(Object(App\Models\User), 'roles')
#2 /home/kingorgg/projects/srpf/app/Controllers/Auth.php(163): SweetORM\Entity->__get('roles')
#3 [internal function]: App\Controllers\Auth->register()
#4 /home/kingorgg/projects/srpf/system/Core/Controller.php(56): call_user_func_array(Array, Array)
#5 /home/kingorgg/projects/srpf/system/Core/Router.php(304): Core\Controller->execute('register', Array)
#6 /home/kingorgg/projects/srpf/system/Core/Router.php(337): Core\Router->invokeController('App\\Controllers...', 'register', Array)
#7 /home/kingorgg/projects/srpf/system/Core/Router.php(374): Core\Router->invokeObject('App\\Controllers...', Array)
#8 /home/kingorgg/projects/srpf/system/bootstrap.php(52): Core\Router->dispatch()
#9 /home/kingorgg/projects/srpf/public_html/index.php(68): require('/home/kingorgg/...')
#10 {main}

           ---------
```

My code in my **Auth Controller** (**Register Method**) is:

``` php
                $user = new User();
                $user->username = $username;
                $user->password = Password::make($password);
                $user->email = $email;
                $user->registered = time();
                $user->registration_ip = $_SERVER['REMOTE_ADDR'];
                $user->activation_string = $activationString;
                $user->roles[] = Role::get(4);
                $user->save();
```

**User Entity:**

``` php
/**
 * User Entity.
 *
 * @author     Daniel Taylor <kingorgg@gmail.com>
 * @copyright  2016 Daniel Taylor
 */

namespace App\Models;

use SweetORM\Entity;
use SweetORM\Structure\Annotation\Column;
use SweetORM\Structure\Annotation\Constraint;
use SweetORM\Structure\Annotation\EntityClass;
use SweetORM\Structure\Annotation\Join;
use SweetORM\Structure\Annotation\JoinColumn;
use SweetORM\Structure\Annotation\JoinTable;
use SweetORM\Structure\Annotation\ManyToMany;
use SweetORM\Structure\Annotation\ManyToOne;
use SweetORM\Structure\Annotation\OneToMany;
use SweetORM\Structure\Annotation\OneToOne;
use SweetORM\Structure\Annotation\Table;

/**
* User Entity.
*
* @EntityClass
* @Table(name="srpf_users")
*/
class User extends Entity
{
    /**
     * @var int
     * @Column(type="integer", name="user_id", primary=true, autoIncrement=true)
     */
    public $user_id;

 // More Code ...

    /**
     * @var Role[]
     * @ManyToMany(targetEntity="App\Models\Role")
     * @JoinTable(name="srpf_users_roles",
     *     column=       @JoinColumn(name="user_id", entityColumn="user_id"),
     *     targetColumn= @JoinColumn(name="role_id", entityColumn="role_id")
     * )
     */
    public $roles;
}
```

**Role Entity:**

``` php
/**
 * Role Entity.
 *
 * @author     Daniel Taylor <kingorgg@gmail.com>
 * @copyright  2016 Daniel Taylor
 */

namespace App\Models;

use SweetORM\Entity;
use SweetORM\Structure\Annotation\Column;
use SweetORM\Structure\Annotation\EntityClass;
use SweetORM\Structure\Annotation\Join;
use SweetORM\Structure\Annotation\JoinColumn;
use SweetORM\Structure\Annotation\JoinTable;
use SweetORM\Structure\Annotation\ManyToMany;
use SweetORM\Structure\Annotation\ManyToOne;
use SweetORM\Structure\Annotation\OneToMany;
use SweetORM\Structure\Annotation\OneToOne;
use SweetORM\Structure\Annotation\Table;

/**
* Role Entity.
*
* @EntityClass
* @Table(name="srpf_roles")
*/
class Role extends Entity
{
    /**
     * @var int
     * @Column(type="integer", name="role_id", primary=true, autoIncrement=true)
     */
    public $role_id;

 // More Code ...

    // Relationships.
    /**
     * @var User[]
     * @ManyToMany(targetEntity="App\Models\User")
     * @JoinTable(name="srpf_users_roles",
     *     column=       @JoinColumn(name="role_id", entityColumn="role_id"),
     *     targetColumn= @JoinColumn(name="user_id", entityColumn="user_id")
     * )
     */
    public $users;
}
```

I'm not sure what I am doing wrong, as I followed what you did in your test folder... Any ideas?

**Comment by tomvlk** [comment]
This kind of error only happends when at the target entity of a defined relationship the property doesn't exists. (when fetched or created).

Anyway, I can't test the code right now, will look into it tomorrow, maybe you can find it already before if you look at the existing of the properties.

Maybe you could debug the ```Role::get(4);``` before adding to the array to see if the needed properties are fetched the right way. 

Anyway, I will look into it tomorrow for sure, maybe it really has to do with the saving of the joining table.

**Comment by Kingorgg** [comment]
I just tested to see if the roles were fetching using:

```php
$role = Role::get(4);
echo Data::pr($role);
```

and it outputs

````
App\Models\Role Object
(
    [role_id] => 4
    [role_name] => New Member
    [role_description] => Site Members that Recently Registered to the Web Site.
    [role_font_color] => Green
    [role_font_weight] => Bold
    [_saved] => 1
)
```

Also, I think I may have found a workaround, unless I stumbled on the actual way to do it... I don't know, I'm currently working on very little sleep.

````php
                $user = new User();
                $user->username = $username;
                $user->password = Password::make($password);
                $user->email = $email;
                $user->registered = time();
                $user->registration_ip = $_SERVER['REMOTE_ADDR'];
                $user->activation_string = $activationString;
                $user->save();

                $findUser= User::find()->where('username', $username)->one();
                $findUser->roles[] = Role::get(4);
                $findUser->save();
```

This seems to have worked. I think the previous way didn't work because it was a new user, so wouldn't have an id assigned to it.

**Comment by tomvlk** [comment]
ye, it doesn't save recursive right now, that may be it indeed.
